### ISSUE TITLE
請問 tauri-apps/tauri-action@v0 預設 Build for Windows 是 64 位元的,在哪裡可以設置32&64位元一起Build?

### ISSUE THREAD

**Issue by beenyan** [lencx/OhMyBox#27]

**Comment by lencx** [comment]
你可以通过以下命令来构建特定平台（具体请查看文档）：

```bash
# 查看
rustup target list

# 添加
rustup target add $target

# 构建
tauri build -t $target
```

**Comment by beenyan** [comment]
沒找到 tauri-apps/tauri-action@v0 支援 windows x86 的文章，手動刻一個。謝謝你的回答。
```yml
- name: Build x86 (windows only)
  if: matrix.platform == 'windows-latest'
  env:
    TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
    TAURI_KEY_PASSWORD: ""
  run: pnpm tauri build --target i686-pc-windows-msvc

- name: Release x86
  uses: softprops/action-gh-release@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: ${{ github.ref_name }}
    draft: false
    files: src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/*
```
